CREATE DATABASE DB_RTH
USE DB_RTH

-- TABLAS BASE DE DATOS---
/* --------- TO REVIEW --------- */
--> Revisar nombres de tablas/campos, tipos y constraints
--> Eliminar DROPs o cambiarlos de posicion para asegurar correcta ejecucion
/* --------- TO REVIEW --------- */

CREATE TABLE MENSAJES(
	CÓDIGO CHAR(4) NOT NULL,
	TEMA INT NOT NULL,
	CONVERSACIÓN INT NOT NULL,
	CONTENIDO NVARCHAR(20) NOT NULL,
	CREADOR NVARCHAR(30) NOT NULL,
	FECHACREACIÓN DATETIME NOT NULL,
		CONSTRAINT PK_MENSAJES PRIMARY KEY(CONVERSACIÓN, CÓDIGO, TEMA),
		CONSTRAINT FK_MENSAJES1 FOREIGN KEY(CÓDIGO,TEMA) REFERENCES CONVERSACIONES(CÓDIGO,TEMA),
		CONSTRAINT FK_MENSAJES2 FOREIGN KEY (CREADOR) REFERENCES USUARIOS(USUARIO)

)

CREATE TABLE TEMAS(
	CÓDIGO CHAR(4) NOT NULL,
	TÍTULO NVARCHAR(10),
	CREADOR NVARCHAR(30) NOT NULL,
	FECHACREACIÓN DATETIME NOT NULL,
		CONSTRAINT PK_TEMAS PRIMARY KEY(CÓDIGO),
		CONSTRAINT FK_TEMAS FOREIGN KEY(CREADOR) REFERENCES USUARIOS(USUARIO)
)

CREATE TABLE [TEMAS SUPERVISADOS](
	USUARIO CHAR(4) NOT NULL,
	TEMA SMALLINT NOT NULL,
		CONSTRAINT PK_SUPERVISADOS PRIMARY KEY(USUARIO, TEMA),
		CONSTRAINT FK_SUPERVISADOS1 FOREIGN KEY(USUARIO) REFERENCES USUARIOS(USUARIO),
		CONSTRAINT FK_SUPERVISADOS2 FOREIGN KEY(TEMA) REFERENCES TEMAS(CÓDIGO)
)

CREATE TABLE MODERADORES(
	USUARIO CHAR(4) NOT NULL,
	TEMA SMALLINT NOT NULL,
		CONSTRAINT PK_MODERADORES PRIMARY KEY(USUARIO, TEMA),
		CONSTRAINT FK_MODERADORES1 FOREIGN KEY(USUARIO) REFERENCES USUARIOS(USUARIO),
		CONSTRAINT FK_MODERADORES2 FOREIGN KEY(TEMA) REFERENCES TEMAS(CÓDIGO)
)

CREATE TABLE CONVERSACIONES(
	CÓDIGO CHAR(4) NOT NULL,
	TEMA INT NOT NULL,
	TÍTULO NVARCHAR(10),
	CREADOR NVARCHAR(30) NOT NULL,
	FECHACREACIÓN DATETIME NOT NULL,
	BLOQUEADO SMALLINT,
		CONSTRAINT PK_CONVERSACIONES PRIMARY KEY(CÓDIGO,TEMA),
		CONSTRAINT FK_CONVERSACIONES1 FOREIGN KEY(CREADOR) REFERENCES USUARIOS(USUARIO),
		CONSTRAINT FK_CONVERSACIONES2 FOREIGN KEY(CÓDIGO) REFERENCES TEMAS(CÓDIGO)
)

CREATE TABLE USUARIOS(
	USUARIO CHAR(4) NOT NULL,
	CONTRASEÑA NVARCHAR(8) NOT NULL,
	CORREO NVARCHAR(25) NOT NULL,
	NICK VARCHAR(15),
	GÉNERO VARCHAR(10),
	PROVINCIA VARCHAR(15) CHECK (PROVINCIA IN ('NAVARRA','GIPUZKOA','BIZKAIA','ARABA','LA RIOJA','CANTABRIA','MADRID','BARCELONA')),
	FECHANAC DATETIME,
	TIPO VARCHAR(10),
		CONSTRAINT PK_USUARIOS PRIMARY KEY(USUARIO)

)

CREATE TABLE [USUARIOS EVENTOS](
	USUARIO CHAR(4) NOT NULL,
	EVENTO INT NOT NULL,
	PERSONAJE NVARCHAR(40) NOT NULL,
		CONSTRAINT PK_USUEVENT PRIMARY KEY(USUARIO, EVENTO),
		CONSTRAINT FK_USUEVENT1 FOREIGN KEY(USUARIO) REFERENCES PERSONAJES(USUARIO),
		CONSTRAINT FK_USUEVENT2 FOREIGN KEY(EVENTO) REFERENCES EVENTOS(CÓDIGO)
)

CREATE TABLE EVENTOS(
	CÓDIGO CHAR(4) NOT NULL,
	NOMBRE NVARCHAR(20) NOT NULL,
	UBICACIÓN VARCHAR(10),
	DETALLES VARCHAR(20),
	COSTE SMALLINT,
	FECHAINICIO DATETIME NOT NULL,
	FECHAFIN DATETIME,
		CONSTRAINT PK_EVENTOS PRIMARY KEY(CÓDIGO),
)

CREATE TABLE REINOS(
	NOMBRE NVARCHAR(20) NOT NULL,
	LEMA VARCHAR(10),
	CAPITAL VARCHAR(15) NOT NULL,
	DESCRIPCIÓN NVARCHAR(25),
	CREADOR NVARCHAR(30) NOT NULL,
	[FORMA GOBIERNO] VARCHAR(15) NOT NULL,
	REY NVARCHAR(20) NOT NULL,
	LEGADO BIT,
	CONTACTO NVARCHAR(20) NOT NULL,
	RELIGIÓN VARCHAR(15),
	EJERCICIO VARCHAR(20),
		CONSTRAINT PK_REINOS PRIMARY KEY(NOMBRE),
		CONSTRAINT FK_REINOS1 FOREIGN KEY(CREADOR) REFERENCES USUARIOS(USUARIO),
		CONSTRAINT FK_REINOS2 FOREIGN KEY(REY) REFERENCES PERSONAJES(USUARIO),
		CONSTRAINT FK_REINOS3 FOREIGN KEY(LEGADO) REFERENCES PERSONAJES(USUARIO)
)

CREATE TABLE PERSONAJES(
	USUARIO CHAR(4) NOT NULL,
	NOMBRE NVARCHAR(20),
	APELLIDO1 NVARCHAR(30),
	APELLIDO2 NVARCHAR(30),
	RAZA VARCHAR(10),
	GÉNERO VARCHAR(10),
	RELIGIÓN VARCHAR(15),
	HISTORIA VARCHAR(40),
	DINERO MONEY,
	CLASE VARCHAR(15) CHECK (CLASE IN ('HÉROES','MERCENARIOS','AVENTUREROS','MAGOS','HECHICEROS')),
	MAGIA VARCHAR(10),
	REINO NVARCHAR(20) NOT NULL,
		CONSTRAINT PK_PERSONAJES PRIMARY KEY(USUARIO),
		CONSTRAINT FK_PERSONAJES FOREIGN KEY(REINO) REFERENCES REINOS(NOMBRE)
)

CREATE TABLE TERRITORIOS(
	NOMBRE NVARCHAR(20) PRIMARY KEY,
	TOPOLOGÍA VARCHAR(15) NOT NULL,
	REINO NVARCHAR(20),
	COMIDA SMALLINT,
	MADERA SMALLINT,
	PIEDRA SMALLINT,
	HIERRO SMALLINT,
	DINERO MONEY,
	POBLACIÓN SMALLINT,
	DEFENSAS SMALLINT,
	ASEDIO SMALLINT,
		CONSTRAINT PK_TERRITORIOS PRIMARY KEY(NOMBRE),
		CONSTRAINT FK_TERRITORIOS1 FOREIGN KEY(NOMBRE) REFERENCES REINOS(CAPITAL),
		CONSTRAINT FK_TERRITORIOS2 FOREIGN KEY(REINO) REFERENCES REINOS(NOMBRE)
)
/* --------- TO REVIEW --------- */
--> Los constraints de claves externas y primarias 
	--deben estar dentro de la definicion de las tablas
--> Verificar nombres de constraints
--> Falta de definicion de claves compuestas
--> Comprobar correcta definicion de claves externas (compuestas y no)
/* --------- TO REVIEW --------- */

-- DEFAULT ---
CREATE DEFAULT TODAY AS GETDATE()
EXEC SP_BINDEFAULT TODAY, 'MENSAJES.FECHACREACIÓN'
EXEC SP_BINDEFAULT TODAY, 'TEMAS.FECHACREACIÓN'
EXEC SP_BINDEFAULT TODAY, 'CONVERSACIONES.FECHACREACIÓN'
--------------------------------------------------------
/* --------- TO REVIEW --------- */
--> Regla FECHAS, ¿Innecesaria o se implementa?
--> Regla CODS, verificar que es el formato deseado para los campos aplicados
/* --------- TO REVIEW --------- */
--REGLAS --
CREATE RULE CODS AS
(@CAMPO LIKE '[0-9][0-9][A-Z][A-Z]')
EXEC SP_BINDRULE CODS, 'MENSAJES.CODIGO'
EXEC SP_BINDRULE CODS, 'TEMAS.CODIGO'
EXEC SP_BINDRULE CODS, 'CONVERSACIONES.CODIGO'
EXEC SP_BINDRULE CODS, 'EVENTOS.CODIGO'

CREATE RULE FECHAS AS (@CAMPO <= GETDATE())
EXEC SP_BINDRULE FECHAS, 'USUARIOS.FECHANAC'
EXEC SP_BINDRULE FECHAS, 'EVENTOS.FECHAINICIO'
EXEC SP_BINDRULE FECHAS, 'EVENTOS.FECHAFIN'
----------------------------------------------------------




