CREATE DATABASE DB_RTH
USE DB_RTH

-- TABLAS BASE DE DATOS---

CREATE TABLE MENSAJES(
	CODIGO CHAR(4) PRIMARY KEY,
	TEMA INT NOT NULL,
	CONVERSACIÓN INT NOT NULL,
	CONTENIDO NVARCHAR(20) NOT NULL,
	CREADOR NVARCHAR(30) NOT NULL,
	FECHACREACIÓN DATETIME NOT NULL
)
DROP TABLE MENSAJES

CREATE TABLE TEMAS(
	CODIGO CHAR(4) PRIMARY KEY,
	TITULO NVARCHAR(10),
	CREADOR NVARCHAR(30) NOT NULL,
	FECHACREACIÓN DATETIME NOT NULL
)
DROP TABLE TEMAS

CREATE TABLE [TEMAS SUPERVISADOS](
	USUARIO CHAR(4) NOT NULL,
	TEMA SMALLINT NOT NULL
)
DROP TABLE [TEMAS SUPERVISADOS]

CREATE TABLE MODERADORES(
	USUARIO CHAR(4) NOT NULL,
	TEMA SMALLINT NOT NULL
)
DROP TABLE MODERADORES

CREATE TABLE CONVERSACIONES(
	CODIGO CHAR(4) NOT NULL,
	TEMA INT NOT NULL,
	TITULO NVARCHAR(10),
	CREADOR NVARCHAR(30) NOT NULL,
	FECHACREACIÓN DATETIME NOT NULL,
	BLOQUEADO SMALLINT
)
DROP TABLE CONVERSACIONES

CREATE TABLE USUARIOS(
	USUARIO CHAR(4) PRIMARY KEY,
	CONTRASEÑA NVARCHAR(8) NOT NULL,
	CORREO NVARCHAR(25) NOT NULL,
	NICK VARCHAR(15),
	GENERO VARCHAR(10),
	PROVINCIA VARCHAR(15) CHECK (PROVINCIA IN ('NAVARRA','GIPUZKOA','BIZKAIA','ARABA','LA RIOJA','CANTABRIA','MADRID','BARCELONA')),
	FECHANAC DATETIME,
	TIPO VARCHAR(10)
)
DROP TABLE USUARIOS


CREATE TABLE [USUARIOS EVENTOS](
	USUARIO CHAR(4) NOT NULL,
	EVENTO INT NOT NULL,
	PERSONAJE NVARCHAR(40) NOT NULL,
)
DROP TABLE [USUARIOS EVENTOS]

CREATE TABLE EVENTOS(
	CODIGO CHAR(4) PRIMARY KEY,
	NOMBRE NVARCHAR(20) NOT NULL,
	UBICACIÓN VARCHAR(10),
	DETALLES VARCHAR(20),
	COSTE SMALLINT,
	FECHAINICIO DATETIME NOT NULL,
	FECHAFIN DATETIME
)
DROP TABLE EVENTOS

CREATE TABLE REINOS(
	NOMBRE NVARCHAR(20) PRIMARY KEY,
	LEMA VARCHAR(10),
	CAPITAL VARCHAR(15) NOT NULL,
	DESCRIPCIÓN NVARCHAR(25),
	CREADOR NVARCHAR(30) NOT NULL,
	[FORMA GOBIERNO] VARCHAR(15) NOT NULL,
	REY NVARCHAR(20) NOT NULL,
	LEGADO BIT,
	CONTACTO NVARCHAR(20) NOT NULL,
	RELIGIÓN VARCHAR(15),
	EJERCICIO VARCHAR(20)
)
DROP TABLE REINOS

CREATE TABLE PERSONAJES(
	USUARIO CHAR(4) PRIMARY KEY,
	NOMBRE NVARCHAR(20),
	APELLIDO1 NVARCHAR(30),
	APELLIDO2 NVARCHAR(30),
	RAZA VARCHAR(10),
	GENERO VARCHAR(10),
	RELIGIÓN VARCHAR(15),
	HISTORIA VARCHAR(40),
	DINERO MONEY,
	CLASE VARCHAR(15) CHECK (CLASE IN ('HÉROES','MERCENARIOS','AVENTUREROS','MAGOS','HECHICEROS')),
	MAGIA VARCHAR(10),
	REINO NVARCHAR(20) NOT NULL,
)
DROP TABLE PERSONAJES

CREATE TABLE TERRITORIOS(
	NOMBRE NVARCHAR(20) PRIMARY KEY,
	TOPOLOGÍA VARCHAR(15) NOT NULL,
	REINO NVARCHAR(20),
	COMIDA SMALLINT,
	MADERA SMALLINT,
	PIEDRA SMALLINT,
	HIERRO SMALLINT,
	DINERO MONEY,
	POBLACIÓN SMALLINT,
	DEFENSAS SMALLINT,
	ASEDIO SMALLINT,
)
DROP TABLE TERRITORIOS
--PRIMARY KEYS --
ALTER TABLE CONVERSACIONES
ADD CONSTRAINT PK_CONVERSACIONES PRIMARY KEY(CODIGO,TEMA)
---------------------------------------------------------

-- FOREIGN KEYS TABLA MENSAJES --
ALTER TABLE MENSAJES
ADD CONSTRAINT FK_MESSAGES FOREIGN KEY(CONVERSACIÓN,TEMA) REFERENCES CONVERSACIONES(CODIGO,TEMA)

ALTER TABLE MENSAJES
ADD CONSTRAINT FK_MESSAGES2 FOREIGN KEY (CREADOR) REFERENCES USUARIOS(USUARIO)
-----------------------------------------------------------------------------------------------

-- FOREIGN KEYS TABLA TEMAS --
ALTER TABLE TEMAS
ADD CONSTRAINT FK_TEMAS FOREIGN KEY(CREADOR) REFERENCES USUARIOS(USUARIO)
-----------------------------------------------------------------------------------------------

--FOREIGN KEYS TABLA CONVERSACIONES --
ALTER TABLE CONVERSACIONES
ADD CONSTRAINT FK_CONVERSATIONS FOREIGN KEY(CREADOR) REFERENCES USUARIO(USUARIO)

ALTER TABLE CONVERSACIONES
ADD CONSTRAINT FK_CONVERSATIONS2 FOREIGN KEY(TEMA) REFERENCES TEMAS(CODIGO)
-----------------------------------------------------------------------------------------------
--FOREIGN KEYS TABLA TEMAS SUPERVISADOS --
ALTER TABLE [TEMAS SUPERVISADOS]
ADD CONSTRAINT FK_SUPERVISADOS FOREIGN KEY(USUARIO) REFERENCES USUARIOS(USUARIO)

ALTER TABLE [TEMAS SUPERVISADOS]
ADD CONSTRAINT FK_SUPERVISADOS2 FOREIGN KEY(TEMA) REFERENCES TEMAS(CODIGO)
-----------------------------------------------------------------------------------------------
--FOREIGN KEYS TABLA MODERADORES --
ALTER TABLE MODERADORES
ADD CONSTRAINT FK_MODERADORES FOREIGN KEY(USUARIO) REFERENCES USUARIOS(USUARIO)

ALTER TABLE MODERADORES
ADD CONSTRAINT FK_MODERADORES2 FOREIGN KEY(TEMA) REFERENCES TEMAS(CODIGO)
-----------------------------------------------------------------------------------------------
--FOREIGN KEYS TABLA USUARIOS EVENTOS --
ALTER TABLE [USUARIOS EVENTOS]
ADD CONSTRAINT FK_USUEVENT FOREIGN KEY(USUARIO) REFERENCES USUARIOS(USUARIO)

ALTER TABLE [USUARIOS EVENTOS]
ADD CONSTRAINT FK_USUEVENT2 FOREIGN KEY(EVENTO) REFERENCES EVENTOS(CODIGO)
-------------------------------------------------------------------------------------------------

--FOREIGN KEYS TABLA PERSONAJES --
ALTER TABLE PERSONAJES
ADD CONSTRAINT FK_CHARACTERS FOREIGN KEY(REINO) REFERENCES REINOS(NOMBRE)
-------------------------------------------------------------------------------------------------

--FOREIGN KEYS TABLA REINOS --
ALTER TABLE REINOS
ADD CONSTRAINT FK_REINOS FOREIGN KEY(REY) REFERENCES PERSONAJES(USUARIO)

ALTER TABLE REINOS
ADD CONSTRAINT FK_REINOS2 FOREIGN KEY(LEGADO) REFERENCES PERSONAJES(USUARIO)
----------------------------------------------------------------------------------------------------
--FOREIGN KEYS TABLA TERRITORIOS --
ALTER TABLE TERRITORIOS
ADD CONSTRAINT FK_TERRITORY FOREIGN KEY(NOMBRE) REFERENCES REINOS(CAPITAL)

ALTER TABLE TERRITORIOS
ADD CONSTRAINT FK_TERRITORY2 FOREIGN KEY(REINO) REFERENCES REINOS(NOMBRE)

-----------------------------------------------------------------------------------------------------

-- DEFAULT ---
CREATE DEFAULT TODAY AS GETDATE()
EXEC SP_BINDEFAULT TODAY, 'MENSAJES.FECHACREACIÓN'
EXEC SP_BINDEFAULT TODAY, 'TEMAS.FECHACREACIÓN'
EXEC SP_BINDEFAULT TODAY, 'CONVERSACIONES.FECHACREACIÓN'
--------------------------------------------------------
--REGLAS --
CREATE RULE CODS AS
(@CAMPO LIKE '[0-9][0-9][A-Z][A-Z]')
EXEC SP_BINDRULE CODS, 'MENSAJES.CODIGO'
EXEC SP_BINDRULE CODS, 'TEMAS.CODIGO'
EXEC SP_BINDRULE CODS, 'CONVERSACIONES.CODIGO'
EXEC SP_BINDRULE CODS, 'EVENTOS.CODIGO'

CREATE RULE FECHAS AS (@CAMPO <= GETDATE())
EXEC SP_BINDRULE FECHAS, 'USUARIOS.FECHANAC'
EXEC SP_BINDRULE FECHAS, 'EVENTOS.FECHAINICIO'
EXEC SP_BINDRULE FECHAS, 'EVENTOS.FECHAFIN'
----------------------------------------------------------




